### ISSUE TITLE
o

### ISSUE THREAD

**Issue by tiimjcb** [aravenad/R2.12-Website#1]

**Comment by aravenad** [comment]
slt mr jocab

le sitte nez pas encor operationel

a+
________________________________
De : tiimjcb ***@***.***>
Envoyé : mercredi 15 mai 2024 14:34
À : aravenad/R2.12-Website ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [aravenad/R2.12-Website] je peux pas acceder au site (Issue #1)


bonjour monsieur bravo

y'a pas de site

svp
